title: Ryan Do
logo: "/images/Profile_pic.png?raw=true"
description: > 
  ## Business Analytics | Machine Learning | Data Science
  <br>
  **Phone:** 0435 079 336 | **Email:** ryan.do.contact@gmail.com
  <br>
  [View My LinkedIn Profile](https://www.linkedin.com/in/ryanism/)
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-T0LE7681KL
